apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: ngopenshiftap
  name: ngopenshiftap
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ngopenshiftap:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/HasseNasse/ngOpenShiftApp.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx-112-rhel7:1-45
        namespace: awesome-angular-app
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
